Firmware SDK: twr_hdc2080
twr_hdc2080
Driver for HDC2080 humidity sensor.
Typedefs
typedef struct twr_hdc2080_t twr_hdc2080_t
HDC2080 instance.
Enumerations
enum twr_hdc2080_event_t {
TWR_HDC2080_EVENT_ERROR = 0,
TWR_HDC2080_EVENT_UPDATE = 1
}
Callback events.
Functions
void twr_hdc2080_init (twr_hdc2080_t *self, twr_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize HDC2080.
void twr_hdc2080_deinit (twr_hdc2080_t *self)
Deinitialize HDC2080.
void twr_hdc2080_set_event_handler (twr_hdc2080_t *self, void(*event_handler)(twr_hdc2080_t *, twr_hdc2080_event_t, void *), void *event_param)
Set callback function.
void twr_hdc2080_set_update_interval (twr_hdc2080_t *self, twr_tick_t interval)
Set measurement interval.
bool twr_hdc2080_measure (twr_hdc2080_t *self)
Start measurement manually.
bool twr_hdc2080_get_humidity_raw (twr_hdc2080_t *self, uint16_t *raw)
Get measured humidity as raw value.
bool twr_hdc2080_get_humidity_percentage (twr_hdc2080_t *self, float *percentage)
Get measured humidity as percentage.
bool twr_hdc2080_get_temperature_raw (twr_hdc2080_t *self, uint16_t *raw)
Get measured temperature as raw value.
bool twr_hdc2080_get_temperature_celsius (twr_hdc2080_t *self, float *celsius)
Get measured temperature in degrees of Celsius.
Detailed Description
Driver for HDC2080 humidity sensor.
Enumeration Type Documentation
twr_hdc2080_event_t
enum twr_hdc2080_event_t
Callback events.
Enumerator
TWR_HDC2080_EVENT_ERROR
Error event.
TWR_HDC2080_EVENT_UPDATE
Update event.
Definition at line 13 of file twr_hdc2080.h.
Function Documentation
twr_hdc2080_deinit()
void twr_hdc2080_deinit (twr_hdc2080_t * self)
Deinitialize HDC2080.
Parameters
[in] self Instance
Definition at line 27 of file twr_hdc2080.c.
twr_hdc2080_get_humidity_percentage()
bool twr_hdc2080_get_humidity_percentage (twr_hdc2080_t * self, float * percentage)
Get measured humidity as percentage.
Parameters
[in] self Instance
[in] percentage Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 84 of file twr_hdc2080.c.
Referenced by twr_tag_humidity_get_humidity_percentage().
twr_hdc2080_get_humidity_raw()
bool twr_hdc2080_get_humidity_raw (twr_hdc2080_t * self, uint16_t * raw)
Get measured humidity as raw value.
Parameters
[in] self Instance
[in] raw Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 72 of file twr_hdc2080.c.
Referenced by twr_hdc2080_get_humidity_percentage(), and twr_tag_humidity_get_humidity_raw().
twr_hdc2080_get_temperature_celsius()
bool twr_hdc2080_get_temperature_celsius (twr_hdc2080_t * self, float * celsius)
Get measured temperature in degrees of Celsius.
Parameters
[in] self Instance
[in] celsius Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 115 of file twr_hdc2080.c.
Referenced by twr_tag_humidity_get_temperature_celsius().
twr_hdc2080_get_temperature_raw()
bool twr_hdc2080_get_temperature_raw (twr_hdc2080_t * self, uint16_t * raw)
Get measured temperature as raw value.
Parameters
[in] self Instance
[in] raw Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 103 of file twr_hdc2080.c.
Referenced by twr_hdc2080_get_temperature_celsius(), and twr_tag_humidity_get_temperature_raw().
twr_hdc2080_init()
void twr_hdc2080_init (twr_hdc2080_t * self, twr_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize HDC2080.
Parameters
[in] self Instance
[in] i2c_channel I2C channel
[in] i2c_address I2C device address
Definition at line 12 of file twr_hdc2080.c.
Referenced by twr_tag_humidity_init().
twr_hdc2080_measure()
bool twr_hdc2080_measure (twr_hdc2080_t * self)
Start measurement manually.
Parameters
[in] self Instance
Returns
true On success
false When other measurement is in progress
Definition at line 58 of file twr_hdc2080.c.
Referenced by twr_hdc2080_get_temperature_celsius(), twr_hdc2080_set_update_interval(), and twr_tag_humidity_measure().
twr_hdc2080_set_event_handler()
void twr_hdc2080_set_event_handler (twr_hdc2080_t * self, void(*)(twr_hdc2080_t *, twr_hdc2080_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 36 of file twr_hdc2080.c.
Referenced by twr_tag_humidity_init().
twr_hdc2080_set_update_interval()
void twr_hdc2080_set_update_interval (twr_hdc2080_t * self, twr_tick_t interval)
Set measurement interval.
Parameters
[in] self Instance
[in] interval Measurement interval
Definition at line 42 of file twr_hdc2080.c.
Referenced by twr_tag_humidity_set_update_interval().