Firmware SDK: twr_sht20
twr_sht20
Driver for SHT20 humidity sensor.
Typedefs
typedef struct twr_sht20_t twr_sht20_t
SHT20 instance.
Enumerations
enum twr_sht20_event_t {
TWR_SHT20_EVENT_ERROR = 0,
TWR_SHT20_EVENT_UPDATE = 1
}
Callback events.
Functions
void twr_sht20_init (twr_sht20_t *self, twr_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize SHT20.
void twr_sht20_deinit (twr_sht20_t *self)
Deinitialize SHT20.
void twr_sht20_set_event_handler (twr_sht20_t *self, void(*event_handler)(twr_sht20_t *, twr_sht20_event_t, void *), void *event_param)
Set callback function.
void twr_sht20_set_update_interval (twr_sht20_t *self, twr_tick_t interval)
Set measurement interval.
bool twr_sht20_measure (twr_sht20_t *self)
Start measurement manually.
bool twr_sht20_get_humidity_raw (twr_sht20_t *self, uint16_t *raw)
Get measured humidity as raw value.
bool twr_sht20_get_humidity_percentage (twr_sht20_t *self, float *percentage)
Get measured humidity as percentage.
bool twr_sht20_get_temperature_raw (twr_sht20_t *self, uint16_t *raw)
Get measured temperature as raw value.
bool twr_sht20_get_temperature_celsius (twr_sht20_t *self, float *celsius)
Get measured temperature in degrees of Celsius.
bool twr_sht20_get_temperature_fahrenheit (twr_sht20_t *self, float *fahrenheit)
Get measured temperature in degrees of Fahrenheit.
bool twr_sht20_get_temperature_kelvin (twr_sht20_t *self, float *kelvin)
Get measured temperature in kelvin.
Detailed Description
Driver for SHT20 humidity sensor.
Enumeration Type Documentation
twr_sht20_event_t
enum twr_sht20_event_t
Callback events.
Enumerator
TWR_SHT20_EVENT_ERROR
Error event.
TWR_SHT20_EVENT_UPDATE
Update event.
Definition at line 13 of file twr_sht20.h.
Function Documentation
twr_sht20_deinit()
void twr_sht20_deinit (twr_sht20_t * self)
Deinitialize SHT20.
Parameters
[in] self Instance
Definition at line 31 of file twr_sht20.c.
Referenced by twr_module_climate_get_pressure_pascal().
twr_sht20_get_humidity_percentage()
bool twr_sht20_get_humidity_percentage (twr_sht20_t * self, float * percentage)
Get measured humidity as percentage.
Parameters
[in] self Instance
[in] percentage Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 86 of file twr_sht20.c.
Referenced by twr_module_climate_get_humidity_percentage(), and twr_tag_humidity_get_humidity_percentage().
twr_sht20_get_humidity_raw()
bool twr_sht20_get_humidity_raw (twr_sht20_t * self, uint16_t * raw)
Get measured humidity as raw value.
Parameters
[in] self Instance
[in] raw Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 74 of file twr_sht20.c.
Referenced by twr_sht20_get_humidity_percentage(), and twr_tag_humidity_get_humidity_raw().
twr_sht20_get_temperature_celsius()
bool twr_sht20_get_temperature_celsius (twr_sht20_t * self, float * celsius)
Get measured temperature in degrees of Celsius.
Parameters
[in] self Instance
[in] celsius Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 121 of file twr_sht20.c.
Referenced by twr_sht20_get_temperature_fahrenheit(), twr_sht20_get_temperature_kelvin(), and twr_tag_humidity_get_temperature_celsius().
twr_sht20_get_temperature_fahrenheit()
bool twr_sht20_get_temperature_fahrenheit (twr_sht20_t * self, float * fahrenheit)
Get measured temperature in degrees of Fahrenheit.
Parameters
[in] self Instance
[out] fahrenheit Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 135 of file twr_sht20.c.
twr_sht20_get_temperature_kelvin()
bool twr_sht20_get_temperature_kelvin (twr_sht20_t * self, float * kelvin)
Get measured temperature in kelvin.
Parameters
[in] self Instance
[out] kelvin Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 149 of file twr_sht20.c.
twr_sht20_get_temperature_raw()
bool twr_sht20_get_temperature_raw (twr_sht20_t * self, uint16_t * raw)
Get measured temperature as raw value.
Parameters
[in] self Instance
[in] raw Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 109 of file twr_sht20.c.
Referenced by twr_sht20_get_temperature_celsius(), and twr_tag_humidity_get_temperature_raw().
twr_sht20_init()
void twr_sht20_init (twr_sht20_t * self, twr_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize SHT20.
Parameters
[in] self Instance
[in] i2c_channel I2C channel
[in] i2c_address I2C device address
Definition at line 16 of file twr_sht20.c.
Referenced by twr_module_climate_get_pressure_pascal(), twr_module_climate_init(), and twr_tag_humidity_init().
twr_sht20_measure()
bool twr_sht20_measure (twr_sht20_t * self)
Start measurement manually.
Parameters
[in] self Instance
Returns
true On success
false When other measurement is in progress
Definition at line 60 of file twr_sht20.c.
Referenced by twr_module_climate_measure_all_sensors(), twr_module_climate_measure_hygrometer(), twr_sht20_get_temperature_kelvin(), twr_sht20_set_update_interval(), and twr_tag_humidity_measure().
twr_sht20_set_event_handler()
void twr_sht20_set_event_handler (twr_sht20_t * self, void(*)(twr_sht20_t *, twr_sht20_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 38 of file twr_sht20.c.
Referenced by twr_module_climate_get_pressure_pascal(), twr_module_climate_init(), and twr_tag_humidity_init().
twr_sht20_set_update_interval()
void twr_sht20_set_update_interval (twr_sht20_t * self, twr_tick_t interval)
Set measurement interval.
Parameters
[in] self Instance
[in] interval Measurement interval
Definition at line 44 of file twr_sht20.c.
Referenced by twr_module_climate_get_pressure_pascal(), twr_module_climate_set_update_interval_all_sensors(), twr_module_climate_set_update_interval_hygrometer(), and twr_tag_humidity_set_update_interval().