Firmware SDK: twr_gfx
twr_gfx
Graphics library.
Data Structures
struct twr_gfx_caps_t
Display size.
struct twr_gfx_driver_t
Display driver interface.
struct twr_gfx_t
Instance.
Enumerations
enum twr_gfx_rotation_t {
TWR_GFX_ROTATION_0 = 0,
TWR_GFX_ROTATION_90 = 1,
TWR_GFX_ROTATION_180 = 2,
TWR_GFX_ROTATION_270 = 3
}
Rotation.
enum twr_gfx_round_corner_t {
TWR_GFX_ROUND_CORNER_RIGHT_TOP = 0x01,
TWR_GFX_ROUND_CORNER_RIGHT_BOTTOM = 0x02,
TWR_GFX_ROUND_CORNER_LEFT_BOTTOM = 0x04,
TWR_GFX_ROUND_CORNER_LEFT_TOP = 0x08
}
Functions
void twr_gfx_init (twr_gfx_t *self, void *display, const twr_gfx_driver_t *driver)
Initialize button.
bool twr_gfx_display_is_ready (twr_gfx_t *self)
Check if display driver is ready for commands.
twr_gfx_caps_t twr_gfx_get_caps (twr_gfx_t *self)
Get Display capabilities.
void twr_gfx_clear (twr_gfx_t *self)
Clear.
void twr_gfx_set_font (twr_gfx_t *self, const twr_font_t *font)
Set font.
void twr_gfx_set_rotation (twr_gfx_t *self, twr_gfx_rotation_t rotation)
Set rotation.
twr_gfx_rotation_t twr_gfx_get_rotation (twr_gfx_t *self)
Get rotation.
void twr_gfx_draw_pixel (twr_gfx_t *self, int x, int y, uint32_t color)
Draw pixel.
int twr_gfx_draw_char (twr_gfx_t *self, int left, int top, uint8_t ch, uint32_t color)
Display draw char.
int twr_gfx_calc_char_width (twr_gfx_t *self, uint8_t ch)
Calc width character.
int twr_gfx_draw_string (twr_gfx_t *self, int left, int top, char *str, uint32_t color)
Display draw string.
int twr_gfx_calc_string_width (twr_gfx_t *self, char *str)
Calc width string.
int twr_gfx_printf (twr_gfx_t *self, int left, int top, uint32_t color, char *format,...)
Display string.
void twr_gfx_draw_line (twr_gfx_t *self, int x0, int y0, int x1, int y1, uint32_t color)
Display draw line.
void twr_gfx_draw_rectangle (twr_gfx_t *self, int x0, int y0, int x1, int y1, uint32_t color)
Display draw rectangle.
void twr_gfx_draw_fill_rectangle (twr_gfx_t *self, int x0, int y0, int x1, int y1, uint32_t color)
Display draw fill rectangle.
void twr_gfx_draw_fill_rectangle_dithering (twr_gfx_t *self, int x0, int y0, int x1, int y1, uint32_t color)
Display draw fill rectangle with a dithering pattern defined in the color parameter.
void twr_gfx_draw_fill_rectangle_dithering_color (twr_gfx_t *self, int x0, int y0, int x1, int y1, uint16_t pattern, uint32_t color_fg, uint32_t color_bg)
Display draw fill rectangle with a dithering pattern defined in the pattern parameter, with the support for multicolor dithering.
void twr_gfx_draw_circle (twr_gfx_t *self, int x0, int y0, int radius, uint32_t color)
Lcd draw circle, using Midpoint circle algorithm.
void twr_gfx_draw_fill_circle (twr_gfx_t *self, int x0, int y0, int radius, uint32_t color)
Lcd draw fill circle, using Midpoint circle algorithm.
void twr_gfx_draw_round_corner (twr_gfx_t *self, int x0, int y0, int radius, twr_gfx_round_corner_t corner, uint32_t color)
Lcd draw round corner, using Midpoint circle algorithm.
void twr_gfx_draw_fill_round_corner (twr_gfx_t *self, int x0, int y0, int radius, twr_gfx_round_corner_t corner, uint32_t color)
Lcd draw fill round corner, using Midpoint circle algorithm.
bool twr_gfx_update (twr_gfx_t *self)
Display update, send data.
Detailed Description
Graphics library.
Enumeration Type Documentation
twr_gfx_rotation_t
enum twr_gfx_rotation_t
Rotation.
Enumerator
TWR_GFX_ROTATION_0
Rotation 0 degrees.
TWR_GFX_ROTATION_90
Rotation 90 degrees.
TWR_GFX_ROTATION_180
Rotation 180 degrees.
TWR_GFX_ROTATION_270
Rotation 270 degrees.
Definition at line 46 of file twr_gfx.h.
twr_gfx_round_corner_t
enum twr_gfx_round_corner_t
Enumerator
TWR_GFX_ROUND_CORNER_RIGHT_TOP
Round corner right top.
TWR_GFX_ROUND_CORNER_RIGHT_BOTTOM
Round corner right bottom.
TWR_GFX_ROUND_CORNER_LEFT_BOTTOM
Round corner left bottom.
TWR_GFX_ROUND_CORNER_LEFT_TOP
Round corner left top.
Definition at line 62 of file twr_gfx.h.
Function Documentation
twr_gfx_calc_char_width()
int twr_gfx_calc_char_width (twr_gfx_t * self, uint8_t ch)
Calc width character.
Parameters
[in] self Instance
Returns
Width of printed character
Definition at line 132 of file twr_gfx.c.
Referenced by twr_gfx_calc_string_width().
twr_gfx_calc_string_width()
int twr_gfx_calc_string_width (twr_gfx_t * self, char * str)
Calc width string.
Parameters
[in] self Instance
[in] *str String to be printed
Returns
Width of printed string
Definition at line 162 of file twr_gfx.c.
twr_gfx_clear()
void twr_gfx_clear (twr_gfx_t * self)
Clear.
Parameters
[in] self Instance
Definition at line 22 of file twr_gfx.c.
Referenced by twr_module_lcd_clear(), and twr_module_lcd_init().
twr_gfx_display_is_ready()
bool twr_gfx_display_is_ready (twr_gfx_t * self)
Check if display driver is ready for commands.
Parameters
[in] self Instance
Returns
true If ready
false If not ready
Definition at line 12 of file twr_gfx.c.
Referenced by twr_module_lcd_is_ready().
twr_gfx_draw_char()
int twr_gfx_draw_char (twr_gfx_t * self, int left, int top, uint8_t ch, uint32_t color)
Display draw char.
Parameters
[in] self Instance
[in] left Pixels from left edge
[in] top Pixels from top edge
[in] ch Char to be printed
[in] color
Returns
Width of printed character
Definition at line 86 of file twr_gfx.c.
Referenced by twr_gfx_draw_string(), and twr_module_lcd_draw_char().
twr_gfx_draw_circle()
void twr_gfx_draw_circle (twr_gfx_t * self, int x0, int y0, int radius, uint32_t color)
Lcd draw circle, using Midpoint circle algorithm.
Parameters
[in] self Instance
[in] x0 Center - pixels from left edge
[in] y0 Center - pixels from top edge
[in] radius In pixels
[in] color
Definition at line 328 of file twr_gfx.c.
Referenced by twr_module_lcd_draw_circle().
twr_gfx_draw_fill_circle()
void twr_gfx_draw_fill_circle (twr_gfx_t * self, int x0, int y0, int radius, uint32_t color)
Lcd draw fill circle, using Midpoint circle algorithm.
Parameters
[in] self Instance
[in] x0 Center - pixels from left edge
[in] y0 Center - pixels from top edge
[in] radius In pixels
[in] color
Definition at line 363 of file twr_gfx.c.
twr_gfx_draw_fill_rectangle()
void twr_gfx_draw_fill_rectangle (twr_gfx_t * self, int x0, int y0, int x1, int y1, uint32_t color)
Display draw fill rectangle.
Parameters
[in] self Instance
[in] x0 Pixels from left edge
[in] y0 Pixels from top edge
[in] x1 Pixels from left edge
[in] y1 Pixels from top edge
[in] color
Definition at line 286 of file twr_gfx.c.
twr_gfx_draw_fill_rectangle_dithering()
void twr_gfx_draw_fill_rectangle_dithering (twr_gfx_t * self, int x0, int y0, int x1, int y1, uint32_t color)
Display draw fill rectangle with a dithering pattern defined in the color parameter.
Parameters
[in] self Instance
[in] x0 Pixels from left edge
[in] y0 Pixels from top edge
[in] x1 Pixels from left edge
[in] y1 Pixels from top edge
[in] color Dithering mask, 16 bits define bit pattern in the 4 by 4 area
Definition at line 298 of file twr_gfx.c.
twr_gfx_draw_fill_rectangle_dithering_color()
void twr_gfx_draw_fill_rectangle_dithering_color (twr_gfx_t * self, int x0, int y0, int x1, int y1, uint16_t pattern, uint32_t color_fg, uint32_t color_bg)
Display draw fill rectangle with a dithering pattern defined in the pattern parameter, with the support for multicolor dithering.
Parameters
[in] self Instance
[in] x0 Pixels from left edge
[in] y0 Pixels from top edge
[in] x1 Pixels from left edge
[in] y1 Pixels from top edge
[in] pattern Dithering mask, 16 bits define bit pattern in the 4 by 4 area
[in] color_fg Color used for the foreground of the rectangle
[in] color_bg Color used for the background of the rectangle
Definition at line 313 of file twr_gfx.c.
twr_gfx_draw_fill_round_corner()
void twr_gfx_draw_fill_round_corner (twr_gfx_t * self, int x0, int y0, int radius, twr_gfx_round_corner_t corner, uint32_t color)
Lcd draw fill round corner, using Midpoint circle algorithm.
Parameters
[in] self Instance
[in] x0 Center - pixels from left edge
[in] y0 Center - pixels from top edge
[in] corner position
[in] radius In pixels
[in] color
Definition at line 442 of file twr_gfx.c.
twr_gfx_draw_line()
void twr_gfx_draw_line (twr_gfx_t * self, int x0, int y0, int x1, int y1, uint32_t color)
Display draw line.
Parameters
[in] self Instance
[in] x0 Pixels from left edge
[in] y0 Pixels from top edge
[in] x1 Pixels from left edge
[in] y1 Pixels from top edge
[in] color
Definition at line 188 of file twr_gfx.c.
Referenced by twr_gfx_draw_fill_circle(), twr_gfx_draw_fill_round_corner(), twr_gfx_draw_rectangle(), and twr_module_lcd_draw_line().
twr_gfx_draw_pixel()
void twr_gfx_draw_pixel (twr_gfx_t * self, int x, int y, uint32_t color)
Draw pixel.
Parameters
[in] self Instance
[in] left Pixels from left edge
[in] top Pixels from top edge
[in] color
Definition at line 42 of file twr_gfx.c.
Referenced by twr_gfx_draw_char(), twr_gfx_draw_circle(), twr_gfx_draw_fill_rectangle(), twr_gfx_draw_fill_rectangle_dithering(), twr_gfx_draw_fill_rectangle_dithering_color(), twr_gfx_draw_line(), twr_gfx_draw_round_corner(), twr_module_lcd_draw_image(), and twr_module_lcd_draw_pixel().
twr_gfx_draw_rectangle()
void twr_gfx_draw_rectangle (twr_gfx_t * self, int x0, int y0, int x1, int y1, uint32_t color)
Display draw rectangle.
Parameters
[in] self Instance
[in] x0 Pixels from left edge
[in] y0 Pixels from top edge
[in] x1 Pixels from left edge
[in] y1 Pixels from top edge
[in] color
Definition at line 278 of file twr_gfx.c.
Referenced by twr_module_lcd_draw_rectangle().
twr_gfx_draw_round_corner()
void twr_gfx_draw_round_corner (twr_gfx_t * self, int x0, int y0, int radius, twr_gfx_round_corner_t corner, uint32_t color)
Lcd draw round corner, using Midpoint circle algorithm.
Parameters
[in] self Instance
[in] x0 Center - pixels from left edge
[in] y0 Center - pixels from top edge
[in] corner position
[in] radius In pixels
[in] color
Definition at line 393 of file twr_gfx.c.
twr_gfx_draw_string()
int twr_gfx_draw_string (twr_gfx_t * self, int left, int top, char * str, uint32_t color)
Display draw string.
Parameters
[in] self Instance
[in] left Pixels from left edge
[in] top Pixels from top edge
[in] *str String to be printed
[in] color
Returns
Width of printed string
Definition at line 152 of file twr_gfx.c.
Referenced by twr_gfx_printf(), and twr_module_lcd_draw_string().
twr_gfx_get_caps()
twr_gfx_caps_t twr_gfx_get_caps (twr_gfx_t * self)
Get Display capabilities.
Parameters
[in] self Instance
Definition at line 17 of file twr_gfx.c.
twr_gfx_get_rotation()
twr_gfx_rotation_t twr_gfx_get_rotation (twr_gfx_t * self)
Get rotation.
Parameters
[in] self Instance
Returns
Rotation of display
Definition at line 37 of file twr_gfx.c.
Referenced by twr_module_lcd_get_rotation().
twr_gfx_init()
void twr_gfx_init (twr_gfx_t * self, void * display, const twr_gfx_driver_t * driver)
Initialize button.
Parameters
[in] self Instance
Definition at line 3 of file twr_gfx.c.
Referenced by twr_module_lcd_init().
twr_gfx_printf()
int twr_gfx_printf (twr_gfx_t * self, int left, int top, uint32_t color, char * format, ...)
Display string.
Parameters
[in] self Instance
[in] left Pixels from left edge
[in] top Pixels from top edge
[in] color
[in] format Format string (printf style)
[in] ... Optional format arguments
Returns
Width of printed string
Definition at line 173 of file twr_gfx.c.
twr_gfx_set_font()
void twr_gfx_set_font (twr_gfx_t * self, const twr_font_t * font)
Set font.
Parameters
[in] self Instance
[in] *font Font
Definition at line 27 of file twr_gfx.c.
Referenced by twr_module_lcd_set_font().
twr_gfx_set_rotation()
void twr_gfx_set_rotation (twr_gfx_t * self, twr_gfx_rotation_t rotation)
Set rotation.
Parameters
[in] self Instance
[in] rotation Rotation of diplay
Definition at line 32 of file twr_gfx.c.
Referenced by twr_module_lcd_set_rotation().
twr_gfx_update()
bool twr_gfx_update (twr_gfx_t * self)
Display update, send data.
Parameters
[in] self Instance
Returns
true On success
false On failure
Definition at line 491 of file twr_gfx.c.
Referenced by twr_module_lcd_update().