Firmware SDK: twr_ds28e17
twr_ds28e17
Driver for DS28E17 (1-wire-to-I2C Master Bridge)
Data Structures
struct twr_ds28e17_t
DS28E17 instance.
Functions
void twr_ds28e17_init (twr_ds28e17_t *self, twr_onewire_t *onewire, uint64_t device_number)
Initialize DS28E17.
void twr_ds28e17_deinit (twr_ds28e17_t *self)
Deinitialize DS28E17.
uint64_t twr_ds28e17_get_device_number (twr_ds28e17_t *self)
Get Device number.
bool twr_ds28e17_enable_sleep_mode (twr_ds28e17_t *self)
Enable Sleep Mode.
bool twr_ds28e17_set_speed (twr_ds28e17_t *self, twr_i2c_speed_t speed)
Set I2C speed.
bool twr_ds28e17_write (twr_ds28e17_t *self, const twr_i2c_transfer_t *transfer)
Write to I2C.
bool twr_ds28e17_read (twr_ds28e17_t *self, const twr_i2c_transfer_t *transfer)
Read from I2C.
bool twr_ds28e17_memory_write (twr_ds28e17_t *self, const twr_i2c_memory_transfer_t *transfer)
Memory write to I2C.
bool twr_ds28e17_memory_read (twr_ds28e17_t *self, const twr_i2c_memory_transfer_t *transfer)
Memory read from I2C.
Detailed Description
Driver for DS28E17 (1-wire-to-I2C Master Bridge)
Function Documentation
twr_ds28e17_deinit()
void twr_ds28e17_deinit (twr_ds28e17_t * self)
Deinitialize DS28E17.
Parameters
[in] self Instance
Definition at line 25 of file twr_ds28e17.c.
Referenced by twr_i2c_deinit().
twr_ds28e17_enable_sleep_mode()
bool twr_ds28e17_enable_sleep_mode (twr_ds28e17_t * self)
Enable Sleep Mode.
Parameters
[in] self Instance
twr_ds28e17_get_device_number()
uint64_t twr_ds28e17_get_device_number (twr_ds28e17_t * self)
Get Device number.
Parameters
[in] self Instance
Definition at line 30 of file twr_ds28e17.c.
twr_ds28e17_init()
void twr_ds28e17_init (twr_ds28e17_t * self, twr_onewire_t * onewire, uint64_t device_number)
Initialize DS28E17.
Parameters
[in] self Instance
[in] Pointer on instance 1-Wire
[in] device_number Device number
Definition at line 14 of file twr_ds28e17.c.
Referenced by twr_i2c_init(), and twr_soil_sensor_get_error().
twr_ds28e17_memory_read()
bool twr_ds28e17_memory_read (twr_ds28e17_t * self, const twr_i2c_memory_transfer_t * transfer)
Memory read from I2C.
Parameters
[in] self Instance
[in] transfer Pointer to I2C memory transfer parameters instance
Returns
true On success
false On failure
Definition at line 107 of file twr_ds28e17.c.
Referenced by twr_i2c_memory_read(), and twr_soil_sensor_get_error().
twr_ds28e17_memory_write()
bool twr_ds28e17_memory_write (twr_ds28e17_t * self, const twr_i2c_memory_transfer_t * transfer)
Memory write to I2C.
Parameters
[in] self Instance
[in] transfer Pointer to I2C memory transfer parameters instance
Returns
true On success
false On failure
Definition at line 82 of file twr_ds28e17.c.
Referenced by twr_i2c_memory_write(), and twr_soil_sensor_get_error().
twr_ds28e17_read()
bool twr_ds28e17_read (twr_ds28e17_t * self, const twr_i2c_transfer_t * transfer)
Read from I2C.
Parameters
[in] self Instance
[in] transfer Pointer to I2C transfer parameters instance
Returns
true On success
false On failure
Definition at line 71 of file twr_ds28e17.c.
Referenced by twr_i2c_read(), and twr_soil_sensor_get_error().
twr_ds28e17_set_speed()
bool twr_ds28e17_set_speed (twr_ds28e17_t * self, twr_i2c_speed_t speed)
Set I2C speed.
Parameters
[in] self Instance
[in] speed I2C communication speed
Definition at line 35 of file twr_ds28e17.c.
Referenced by twr_i2c_set_speed().
twr_ds28e17_write()
bool twr_ds28e17_write (twr_ds28e17_t * self, const twr_i2c_transfer_t * transfer)
Write to I2C.
Parameters
[in] self Instance
[in] transfer Pointer to I2C transfer parameters instance
Returns
true On success
false On failure
Definition at line 60 of file twr_ds28e17.c.
Referenced by twr_i2c_write(), and twr_soil_sensor_get_error().