Firmware SDK: twr_sha256
twr_sha256
Library for SHA256 hash.
Functions
void twr_sha256_init (twr_sha256_t *self)
Initialize SHA256 structure.
void twr_sha256_update (twr_sha256_t *self, const void *buffer, size_t length)
Compute SHA256 from data.
void twr_sha256_final (twr_sha256_t *self, uint8_t *hash, bool little_endian)
Finalize SHA256 computation and read the final hash.
Detailed Description
Library for SHA256 hash.
Function Documentation
twr_sha256_final()
void twr_sha256_final (twr_sha256_t * self, uint8_t * hash, bool little_endian)
Finalize SHA256 computation and read the final hash.
Parameters
[in] self SHA256 instance
[in] hash pointer to the array where the hash will be copied
[in] little_endian endian format
Definition at line 58 of file twr_sha256.c.
Referenced by twr_config_load(), and twr_config_save().
twr_sha256_init()
void twr_sha256_init (twr_sha256_t * self)
Initialize SHA256 structure.
Parameters
[in] self SHA256 instance
Definition at line 26 of file twr_sha256.c.
Referenced by twr_config_load(), and twr_config_save().
twr_sha256_update()
void twr_sha256_update (twr_sha256_t * self, const void * buffer, size_t length)
Compute SHA256 from data.
Parameters
[in] self SHA256 instance
[in] buffer data
[in] length data length
Definition at line 40 of file twr_sha256.c.
Referenced by twr_config_load(), and twr_config_save().