Firmware SDK: twr_tick
twr_tick
Timestamp functions.
Macros
#define TWR_TICK_INFINITY UINT64_C(0xffffffffffffffff)
Maximum timestamp value.
Typedefs
typedef uint64_t twr_tick_t
Timestamp data type.
Functions
twr_tick_t twr_tick_get (void)
Get absolute timestamp since start of program.
void twr_tick_wait (twr_tick_t delay)
Delay execution for specified amount of ticks.
void twr_tick_increment_irq (twr_tick_t delta)
Detailed Description
Timestamp functions.
Function Documentation
twr_tick_get()
twr_tick_t twr_tick_get (void)
Get absolute timestamp since start of program.
Returns
Timestamp in milliseconds
Definition at line 7 of file twr_tick.c.
Referenced by twr_aes_iv_from_uint8(), twr_aes_key_derivation(), twr_cy8cmbr3102_set_scan_interval(), twr_ds28e17_memory_read(), twr_eeprom_get_size(), twr_hdc2080_get_temperature_celsius(), twr_hts221_get_humidity_percentage(), twr_i2c_init(), twr_i2c_memory_read_16b(), twr_lp8_calibration(), twr_lp8_init(), twr_module_battery_is_present(), twr_module_lcd_draw_image(), twr_module_rs485_measure(), twr_mpl3115a2_get_pressure_pascal(), twr_mpl3115a2_init(), twr_opt3001_get_illuminance_lux(), twr_pyq1648_set_blank_period(), twr_ramp_get(), twr_ramp_start(), twr_sc16is740_read(), twr_scheduler_plan_current_from_now(), twr_scheduler_plan_from_now(), twr_scheduler_run(), twr_sht20_get_temperature_kelvin(), twr_sht30_get_temperature_kelvin(), twr_spirit1_set_rx_timeout(), twr_spirit1_sleep(), twr_sps30_get_typical_particle_size(), twr_sps30_measure(), twr_tick_wait(), twr_tmp112_get_temperature_kelvin(), twr_uart_read(), and twr_zssc3123_unlock_eeprom().
twr_tick_wait()
void twr_tick_wait (twr_tick_t delay)
Delay execution for specified amount of ticks.
Parameters
[in] delay Number of ticks to wait
Definition at line 23 of file twr_tick.c.