Firmware SDK: twr_ls013b7dh03
twr_ls013b7dh03
Driver for LS013B7DH03 1.28" HR-TFT Memory LCD.
Data Structures
struct twr_ls013b7dh03_t
Instance.
Macros
#define TWR_LS013B7DH03_WIDTH 128
#define TWR_LS013B7DH03_HEIGHT 128
#define TWR_LS013B7DH03_FRAMEBUFFER_SIZE (1 + ((1+(TWR_LS013B7DH03_WIDTH / 8)+1) * TWR_LS013B7DH03_HEIGHT) + 1)
Functions
void twr_ls013b7dh03_init (twr_ls013b7dh03_t *self, bool(*pin_cs_set)(bool state))
Initialize lcd driver.
twr_gfx_caps_t twr_ls013b7dh03_get_caps (twr_ls013b7dh03_t *self)
Get capabilities.
bool twr_ls013b7dh03_is_ready (twr_ls013b7dh03_t *self)
Check if lcd is ready for commands.
void twr_ls013b7dh03_clear (twr_ls013b7dh03_t *self)
Clear.
void twr_ls013b7dh03_draw_pixel (twr_ls013b7dh03_t *self, int x, int y, uint32_t color)
Lcd draw pixel.
uint32_t twr_ls013b7dh03_get_pixel (twr_ls013b7dh03_t *self, int x, int y)
Lcd get pixel.
bool twr_ls013b7dh03_update (twr_ls013b7dh03_t *self)
Lcd update, send data.
bool twr_ls013b7dh03_clear_memory_command (twr_ls013b7dh03_t *self)
Send Lcd clear memory command.
const twr_gfx_driver_t * twr_ls013b7dh03_get_driver (void)
Get Lcd driver.
Detailed Description
Driver for LS013B7DH03 1.28" HR-TFT Memory LCD.
Function Documentation
twr_ls013b7dh03_clear()
void twr_ls013b7dh03_clear (twr_ls013b7dh03_t * self)
Clear.
Parameters
[in] self Instance
Definition at line 52 of file twr_ls013b7dh03.c.
Referenced by twr_ls013b7dh03_get_driver().
twr_ls013b7dh03_clear_memory_command()
bool twr_ls013b7dh03_clear_memory_command (twr_ls013b7dh03_t * self)
Send Lcd clear memory command.
Returns
true On success
false On failure
Definition at line 151 of file twr_ls013b7dh03.c.
twr_ls013b7dh03_draw_pixel()
void twr_ls013b7dh03_draw_pixel (twr_ls013b7dh03_t * self, int x, int y, uint32_t color)
Lcd draw pixel.
Parameters
[in] self Instance
[in] left Pixels from left edge
[in] top Pixels from top edge
[in] color Pixels state
Definition at line 66 of file twr_ls013b7dh03.c.
Referenced by twr_ls013b7dh03_get_driver().
twr_ls013b7dh03_get_caps()
twr_gfx_caps_t twr_ls013b7dh03_get_caps (twr_ls013b7dh03_t * self)
Get capabilities.
Parameters
[in] self Instance
Definition at line 36 of file twr_ls013b7dh03.c.
Referenced by twr_ls013b7dh03_get_driver().
twr_ls013b7dh03_get_pixel()
uint32_t twr_ls013b7dh03_get_pixel (twr_ls013b7dh03_t * self, int x, int y)
Lcd get pixel.
Parameters
[in] self Instance
[in] left Pixels from left edge
[in] top Pixels from top edge
[in] color Pixels state
Definition at line 87 of file twr_ls013b7dh03.c.
Referenced by twr_ls013b7dh03_get_driver().
twr_ls013b7dh03_init()
void twr_ls013b7dh03_init (twr_ls013b7dh03_t * self, bool(*)(bool state) pin_cs_set)
Initialize lcd driver.
Parameters
[in] self Instance
Definition at line 13 of file twr_ls013b7dh03.c.
Referenced by twr_module_lcd_init().
twr_ls013b7dh03_is_ready()
bool twr_ls013b7dh03_is_ready (twr_ls013b7dh03_t * self)
Check if lcd is ready for commands.
Parameters
[in] self Instance
Returns
true If ready
false If not ready
Definition at line 45 of file twr_ls013b7dh03.c.
Referenced by twr_ls013b7dh03_get_driver().
twr_ls013b7dh03_update()
bool twr_ls013b7dh03_update (twr_ls013b7dh03_t * self)
Lcd update, send data.
Parameters
[in] self Instance
Returns
true On success
false On failure
Definition at line 108 of file twr_ls013b7dh03.c.
Referenced by twr_ls013b7dh03_get_driver().