Firmware SDK: twr_ds18b20
twr_ds18b20
Driver for 1wire ds18b20.
Typedefs
typedef struct twr_ds18b20_t twr_ds18b20_t
BigClown ds18b20 instance.
typedef struct twr_ds18b20_sensor_t twr_ds18b20_sensor_t
Enumerations
enum twr_ds18b20_event_t {
TWR_DS18B20_EVENT_ERROR = -1 ,
TWR_DS18B20_EVENT_UPDATE = 0
}
Callback events.
Functions
void twr_ds18b20_init_single (twr_ds18b20_t *self, twr_ds18b20_resolution_bits_t resolution)
Initialize single ds18b20 over channel B on Sensor Module.
void twr_ds18b20_init_multiple (twr_ds18b20_t *self, twr_ds18b20_sensor_t *sensors, int sensor_count, twr_ds18b20_resolution_bits_t resolution)
Initialize multiple ds18b20 over channel B on Sensor Module.
void twr_ds18b20_init (twr_ds18b20_t *self, twr_onewire_t *onewire, twr_ds18b20_sensor_t *sensors, int sensor_count, twr_ds18b20_resolution_bits_t resolution)
Initialize ds18b20.
void twr_ds18b20_set_event_handler (twr_ds18b20_t *self, void(*event_handler)(twr_ds18b20_t *, uint64_t _device_address, twr_ds18b20_event_t, void *), void *event_param)
Set callback function.
void twr_ds18b20_set_update_interval (twr_ds18b20_t *self, twr_tick_t interval)
Set measurement interval.
bool twr_ds18b20_measure (twr_ds18b20_t *self)
Start measurement manually.
bool twr_ds18b20_get_temperature_raw (twr_ds18b20_t *self, uint64_t device_address, int16_t *raw)
Get measured temperature in degrees of Celsius.
bool twr_ds18b20_get_temperature_celsius (twr_ds18b20_t *self, uint64_t _device_address, float *celsius)
Get measured temperature in degrees of Celsius.
int twr_ds18b20_get_index_by_device_address (twr_ds18b20_t *self, uint64_t device_address)
Get device index by its device address.
uint64_t twr_ds182b0_get_short_address (twr_ds18b20_t *self, uint8_t index)
Get device index by its device address.
int twr_ds18b20_get_sensor_found (twr_ds18b20_t *self)
Get number of found sensor.
void twr_ds18b20_rescan (twr_ds18b20_t *self)
Request to rescan the bus.
void twr_ds18b20_set_power_dynamic (twr_ds18b20_t *self, bool on)
Set power dynamic, Turns VDD on and pull 4k7 only for measurement.
Detailed Description
Driver for 1wire ds18b20.
Enumeration Type Documentation
twr_ds18b20_event_t
enum twr_ds18b20_event_t
Callback events.
Enumerator
TWR_DS18B20_EVENT_ERROR
Error event.
TWR_DS18B20_EVENT_UPDATE
Update event.
Definition at line 15 of file twr_ds18b20.h.
Function Documentation
twr_ds182b0_get_short_address()
uint64_t twr_ds182b0_get_short_address (twr_ds18b20_t * self, uint8_t index)
Get device index by its device address.
Parameters
[in] self Instance
[in] index Index
Returns
short addres or 0
Definition at line 106 of file twr_ds18b20.c.
twr_ds18b20_get_index_by_device_address()
int twr_ds18b20_get_index_by_device_address (twr_ds18b20_t * self, uint64_t device_address)
Get device index by its device address.
Parameters
[in] self Instance
[in] device_address 64b device address
Definition at line 93 of file twr_ds18b20.c.
Referenced by twr_ds18b20_get_temperature_celsius(), and twr_ds18b20_get_temperature_raw().
twr_ds18b20_get_sensor_found()
int twr_ds18b20_get_sensor_found (twr_ds18b20_t * self)
Get number of found sensor.
Parameters
[in] self Instance
Definition at line 120 of file twr_ds18b20.c.
twr_ds18b20_get_temperature_celsius()
bool twr_ds18b20_get_temperature_celsius (twr_ds18b20_t * self, uint64_t _device_address, float * celsius)
Get measured temperature in degrees of Celsius.
Parameters
[in] self Instance
[in] device_address 64b device address
[in] celsius Pointer to variables where results will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 166 of file twr_ds18b20.c.
twr_ds18b20_get_temperature_raw()
bool twr_ds18b20_get_temperature_raw (twr_ds18b20_t * self, uint64_t device_address, int16_t * raw)
Get measured temperature in degrees of Celsius.
Parameters
[in] self Instance
[in] device_address 64b device address
Get measured temperature as raw values
Returns
true When value is valid
false When value is invalid
Definition at line 147 of file twr_ds18b20.c.
twr_ds18b20_init()
void twr_ds18b20_init (twr_ds18b20_t * self, twr_onewire_t * onewire, twr_ds18b20_sensor_t * sensors, int sensor_count, twr_ds18b20_resolution_bits_t resolution)
Initialize ds18b20.
Parameters
[in] self Instance
[in] onewire Pointer on instance 1-Wire
[in] sensors Sensor array
[in] sensor_count Max count sensors
[in] resolution Resolution
Definition at line 36 of file twr_ds18b20.c.
Referenced by twr_ds18b20_init_multiple(), and twr_ds18b20_init_single().
twr_ds18b20_init_multiple()
void twr_ds18b20_init_multiple (twr_ds18b20_t * self, twr_ds18b20_sensor_t * sensors, int sensor_count, twr_ds18b20_resolution_bits_t resolution)
Initialize multiple ds18b20 over channel B on Sensor Module.
Parameters
[in] self Instance
[in] sensors Sensor array
[in] sensor_count Max count sensors
[in] resolution Resolution
Definition at line 30 of file twr_ds18b20.c.
twr_ds18b20_init_single()
void twr_ds18b20_init_single (twr_ds18b20_t * self, twr_ds18b20_resolution_bits_t resolution)
Initialize single ds18b20 over channel B on Sensor Module.
Parameters
[in] self Instance
[in] resolution Resolution
Definition at line 23 of file twr_ds18b20.c.
twr_ds18b20_measure()
bool twr_ds18b20_measure (twr_ds18b20_t * self)
Start measurement manually.
Parameters
[in] self Instance
Returns
true On success
false When other measurement is in progress
Definition at line 79 of file twr_ds18b20.c.
Referenced by twr_ds18b20_set_update_interval().
twr_ds18b20_set_event_handler()
void twr_ds18b20_set_event_handler (twr_ds18b20_t * self, void(*)(twr_ds18b20_t *, uint64_t _device_address, twr_ds18b20_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 56 of file twr_ds18b20.c.
twr_ds18b20_set_power_dynamic()
void twr_ds18b20_set_power_dynamic (twr_ds18b20_t * self, bool on)
Set power dynamic, Turns VDD on and pull 4k7 only for measurement.
Parameters
[in] self Instance
[in] on True enable dynamic, False disable dynamic
Definition at line 142 of file twr_ds18b20.c.
twr_ds18b20_set_update_interval()
void twr_ds18b20_set_update_interval (twr_ds18b20_t * self, twr_tick_t interval)
Set measurement interval.
Parameters
[in] self Instance
[in] interval Measurement interval
Definition at line 63 of file twr_ds18b20.c.