Firmware SDK: twr_timer
twr_timer
Driver for timer.
Functions
void twr_timer_init (void)
Initialize timer.
void twr_timer_start (void)
Start timer.
uint16_t twr_timer_get_microseconds (void)
Get actual tick of timer.
void twr_timer_delay (uint16_t microseconds)
Relative delay.
void twr_timer_clear (void)
Clear timer counter.
void twr_timer_stop (void)
Stop timer.
bool twr_timer_set_irq_handler (TIM_TypeDef *tim, void(*irq_handler)(void *), void *irq_param)
Register timer IRQ handler.
void twr_timer_clear_irq_handler (TIM_TypeDef *tim)
Unregister timer IRQ handler.
Variables
const uint16_t _twr_timer_prescaler_lut [3]
Detailed Description
Driver for timer.
Function Documentation
twr_timer_clear_irq_handler()
void twr_timer_clear_irq_handler (TIM_TypeDef * tim)
Unregister timer IRQ handler.
Parameters
[in] tim Timer, e.g. TIM3
Definition at line 74 of file twr_timer.c.
twr_timer_delay()
void twr_timer_delay (uint16_t microseconds) inline
Relative delay.
Parameters
[in] tick tick to delay in us
Definition at line 59 of file twr_timer.c.
Referenced by twr_delay_us(), twr_module_battery_is_present(), twr_module_encoder_is_present(), twr_spi_async_transfer(), twr_spi_transfer(), twr_spirit1_sleep(), twr_switch_set_pull_advance_time(), twr_tag_nfc_init(), twr_zssc3123_eeprom_read(), and twr_zssc3123_eeprom_write().
twr_timer_get_microseconds()
uint16_t twr_timer_get_microseconds (void) inline
Get actual tick of timer.
Returns
Actual state of timer counter (microseconds from start)
Definition at line 54 of file twr_timer.c.
Referenced by twr_pyq1648_set_blank_period(), twr_spirit1_sleep(), and twr_timer_delay().
twr_timer_set_irq_handler()
bool twr_timer_set_irq_handler (TIM_TypeDef * tim, void(*)(void *) irq_handler, void * irq_param)
Register timer IRQ handler.
Parameters
[in] tim Timer, e.g. TIM3
[in] irq_handler pointer to IRQ handler function
[in] irq_param parameter
Definition at line 86 of file twr_timer.c.
Referenced by twr_rf_ook_send().