Firmware SDK: twr_sgp30
twr_sgp30
Driver for SGP30 VOC gas sensor.
Typedefs
typedef struct twr_sgp30_t twr_sgp30_t
SGP30 instance.
Enumerations
enum twr_sgp30_event_t {
TWR_SGP30_EVENT_ERROR = 0,
TWR_SGP30_EVENT_UPDATE = 1
}
Callback events.
Functions
void twr_sgp30_init (twr_sgp30_t *self, twr_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize SGP30.
void twr_sgp30_deinit (twr_sgp30_t *self)
Deinitialize SGP30.
void twr_sgp30_set_event_handler (twr_sgp30_t *self, void(*event_handler)(twr_sgp30_t *, twr_sgp30_event_t, void *), void *event_param)
Set callback function.
void twr_sgp30_set_update_interval (twr_sgp30_t *self, twr_tick_t interval)
Set measurement interval.
bool twr_sgp30_measure (twr_sgp30_t *self)
Start measurement manually.
bool twr_sgp30_get_co2eq_ppm (twr_sgp30_t *self, uint16_t *ppm)
Get measured CO2eq in ppm (parts per million)
bool twr_sgp30_get_tvoc_ppb (twr_sgp30_t *self, uint16_t *ppb)
Get measured TVOC in ppb (parts per billion)
float twr_sgp30_set_compensation (twr_sgp30_t *self, float *t_celsius, float *rh_percentage)
Set sensor compensation (absolute humidity is calculated from temperature and relative humidity)
Detailed Description
Driver for SGP30 VOC gas sensor.
Enumeration Type Documentation
twr_sgp30_event_t
enum twr_sgp30_event_t
Callback events.
Enumerator
TWR_SGP30_EVENT_ERROR
Error event.
TWR_SGP30_EVENT_UPDATE
Update event.
Definition at line 13 of file twr_sgp30.h.
Function Documentation
twr_sgp30_deinit()
void twr_sgp30_deinit (twr_sgp30_t * self)
Deinitialize SGP30.
Parameters
[in] self Instance
Definition at line 32 of file twr_sgp30.c.
twr_sgp30_get_co2eq_ppm()
bool twr_sgp30_get_co2eq_ppm (twr_sgp30_t * self, uint16_t * ppm)
Get measured CO2eq in ppm (parts per million)
Parameters
[in] self Instance
[out] ppm Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 80 of file twr_sgp30.c.
Referenced by twr_tag_voc_get_co2eq_ppm().
twr_sgp30_get_tvoc_ppb()
bool twr_sgp30_get_tvoc_ppb (twr_sgp30_t * self, uint16_t * ppb)
Get measured TVOC in ppb (parts per billion)
Parameters
[in] self Instance
[out] ppb Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 92 of file twr_sgp30.c.
Referenced by twr_tag_voc_get_tvoc_ppb().
twr_sgp30_init()
void twr_sgp30_init (twr_sgp30_t * self, twr_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize SGP30.
Parameters
[in] self Instance
[in] i2c_channel I2C channel
[in] i2c_address I2C device address
Definition at line 17 of file twr_sgp30.c.
Referenced by twr_tag_voc_init().
twr_sgp30_measure()
bool twr_sgp30_measure (twr_sgp30_t * self)
Start measurement manually.
Parameters
[in] self Instance
Returns
true On success
false When other measurement is in progress
Definition at line 61 of file twr_sgp30.c.
Referenced by twr_sgp30_set_compensation(), twr_sgp30_set_update_interval(), and twr_tag_voc_measure().
twr_sgp30_set_compensation()
float twr_sgp30_set_compensation (twr_sgp30_t * self, float * t_celsius, float * rh_percentage)
Set sensor compensation (absolute humidity is calculated from temperature and relative humidity)
Parameters
[in] self Instance
[in] t_celsius Pointer to variable holding temperature in degrees of celsius (must be NULL if not available)
[in] rh_percentage Pointer to variable holding relative humidity in percentage (must be NULL if not available)
Returns
Absolute humidity in grams per cubic meter
Definition at line 104 of file twr_sgp30.c.
Referenced by twr_tag_voc_set_compensation().
twr_sgp30_set_event_handler()
void twr_sgp30_set_event_handler (twr_sgp30_t * self, void(*)(twr_sgp30_t *, twr_sgp30_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 39 of file twr_sgp30.c.
Referenced by twr_tag_voc_set_event_handler().
twr_sgp30_set_update_interval()
void twr_sgp30_set_update_interval (twr_sgp30_t * self, twr_tick_t interval)
Set measurement interval.
Parameters
[in] self Instance
[in] interval Measurement interval
Definition at line 45 of file twr_sgp30.c.
Referenced by twr_tag_voc_set_update_interval().