Firmware SDK: twr_hc_sr04
twr_hc_sr04
Driver for HC-SR04 ultrasonic range sensor.
Typedefs
typedef struct twr_hc_sr04_t twr_hc_sr04_t
HC-SR04 instance.
Enumerations
enum twr_hc_sr04_event_t {
TWR_HC_SR04_EVENT_ERROR = 0,
TWR_HC_SR04_EVENT_UPDATE = 1
}
enum twr_hc_sr04_echo_t {
TWR_HC_SR04_ECHO_P5 = TWR_GPIO_P5,
TWR_HC_SR04_ECHO_P8 = TWR_GPIO_P8
}
Functions
void twr_hc_sr04_init_sensor_module (twr_hc_sr04_t *self)
Initialize HC-SR04 for sensor module.
void twr_hc_sr04_init (twr_hc_sr04_t *self, twr_gpio_channel_t trig, twr_hc_sr04_echo_t echo)
Initialize HC-SR04.
void twr_hc_sr04_set_event_handler (twr_hc_sr04_t *self, void(*event_handler)(twr_hc_sr04_t *, twr_hc_sr04_event_t, void *), void *event_param)
Set callback function.
void twr_hc_sr04_set_update_interval (twr_hc_sr04_t *self, twr_tick_t interval)
Set measurement interval.
bool twr_hc_sr04_measure (twr_hc_sr04_t *self)
Start measurement manually.
bool twr_hc_sr04_get_distance_millimeter (twr_hc_sr04_t *self, float *millimeter)
Get measured distance in millimeters.
Detailed Description
Driver for HC-SR04 ultrasonic range sensor.
Enumeration Type Documentation
twr_hc_sr04_event_t
enum twr_hc_sr04_event_t
Enumerator
TWR_HC_SR04_EVENT_ERROR
Error event.
TWR_HC_SR04_EVENT_UPDATE
Update event.
Definition at line 12 of file twr_hc_sr04.h.
Function Documentation
twr_hc_sr04_get_distance_millimeter()
bool twr_hc_sr04_get_distance_millimeter (twr_hc_sr04_t * self, float * millimeter)
Get measured distance in millimeters.
Parameters
[in] self Instance
[out] millimeter Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 190 of file twr_hc_sr04.c.
twr_hc_sr04_init()
void twr_hc_sr04_init (twr_hc_sr04_t * self, twr_gpio_channel_t trig, twr_hc_sr04_echo_t echo)
Initialize HC-SR04.
Parameters
[in] self Instance
[in] echo Pin
[in] trig Pin
Definition at line 19 of file twr_hc_sr04.c.
Referenced by twr_hc_sr04_init_sensor_module().
twr_hc_sr04_init_sensor_module()
void twr_hc_sr04_init_sensor_module (twr_hc_sr04_t * self)
Initialize HC-SR04 for sensor module.
Parameters
[in] self Instance
Definition at line 14 of file twr_hc_sr04.c.
twr_hc_sr04_measure()
bool twr_hc_sr04_measure (twr_hc_sr04_t * self)
Start measurement manually.
Parameters
[in] self Instance
Returns
true On success
false When other measurement is in progress
Definition at line 114 of file twr_hc_sr04.c.
Referenced by twr_hc_sr04_get_distance_millimeter(), and twr_hc_sr04_set_update_interval().
twr_hc_sr04_set_event_handler()
void twr_hc_sr04_set_event_handler (twr_hc_sr04_t * self, void(*)(twr_hc_sr04_t *, twr_hc_sr04_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 92 of file twr_hc_sr04.c.
twr_hc_sr04_set_update_interval()
void twr_hc_sr04_set_update_interval (twr_hc_sr04_t * self, twr_tick_t interval)
Set measurement interval.
Parameters
[in] self Instance
[in] interval Measurement interval
Definition at line 98 of file twr_hc_sr04.c.